config/routes.rb
Rails.application.routes.draw do
  resources :collection_points
  resources :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root :to => 'users#index'
  namespace :api do
    namespace :v1 do
      post 'authenticate', to: 'authentication#authenticate'
      resources :users, only: :index 
      resources :collection_points, only: :index do
        collection do
          get :assign_points
        end
      end
    end
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collection_point.rb
class CollectionPoint < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/api/base_controller.rb
module Api
    class BaseController < ApplicationController
      before_action :authenticate_request
  
      def authenticate_request
        @current_user = AuthorizeApiRequest.call(request.headers).result
        render json: { error: 'Not Authorized' }, status: 401 unless @current_user
      end
    end
  end

app/controllers/api/v1/authentication_controller.rb
module Api
    module V1
      class AuthenticationController < Api::BaseController
        protect_from_forgery with: :null_session
        skip_before_action :authenticate_request
  
        def authenticate
          command = AuthenticateUser.call(params[:email], params[:password])
          if command.success?
            render json: { auth_token: command.result, user: command.user }
          else
            render json: { error: command.errors }, status: :unauthorized
          end
        end
      end
    end
  end
  

app/controllers/api/v1/collection_points_controller.rb
module Api
    module V1
      class CollectionPointsController < Api::BaseController
        skip_before_action :authenticate_request
  
        def index
          @collection_points = CollectionPoint.all
          render json: @collection_points
        end

        def assign_points
          @user = User.find_by(id: params[:user_id])
          @user.points += 10
          @user.save
          render json:  @user
        end
      end
    end
  end
  

app/controllers/api/v1/users_controller.rb
module Api
    module V1
      class UsersController < Api::BaseController
        skip_before_action :authenticate_request
  
        def index
          @users = User.all
          render json: @users
        end
      end
    end
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/collection_points_controller.rb
class CollectionPointsController < InheritedResources::Base

  private

    def collection_point_params
      params.require(:collection_point).permit(:name, :direction)
    end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base
  private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :points, :firstname, :lastname)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collection_points_helper.rb
module CollectionPointsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/collection_points/_form.html.erb
<%= form_with(model: collection_point, local: true) do |form| %>
  <% if collection_point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(collection_point.errors.count, "error") %> prohibited this collection_point from being saved:</h2>

      <ul>
      <% collection_point.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :collection_point_name %>
  </div>

  <div class="field">
    <%= form.label :direction %>
    <%= form.text_field :direction, id: :collection_point_direction %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/collection_points/edit.html.erb
<h1>Editing Collection Point</h1>

<%= render 'form', collection_point: @collection_point %>

<%= link_to 'Show', @collection_point %> |
<%= link_to 'Back', collection_points_path %>

app/views/collection_points/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Collection Points</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Direction</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @collection_points.each do |collection_point| %>
      <tr>
        <td><%= collection_point.name %></td>
        <td><%= collection_point.direction %></td>
        <td><%= link_to 'Show', collection_point %></td>
        <td><%= link_to 'Edit', edit_collection_point_path(collection_point) %></td>
        <td><%= link_to 'Destroy', collection_point, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Collection Point', new_collection_point_path %>

app/views/collection_points/new.html.erb
<h1>New Collection Point</h1>

<%= render 'form', collection_point: @collection_point %>

<%= link_to 'Back', collection_points_path %>

app/views/collection_points/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @collection_point.name %>
</p>

<p>
  <strong>Direction:</strong>
  <%= @collection_point.direction %>
</p>

<%= link_to 'Edit', edit_collection_point_path(@collection_point) %> |
<%= link_to 'Back', collection_points_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recycling</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :points %>
    <%= form.number_field :points, id: :user_points, max: user.points %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Buy Product</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Points</th>
      <th>Firstname</th>
      <th>Lastname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.points %></td>
        <td><%= user.firstname %></td>
        <td><%= user.lastname %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Buy Product', edit_user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Points:</strong>
  <%= @user.points %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @user.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>